1. Create a NumPy array of integers from 1 to 10

In [54]:
import numpy as np
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create a 2x3 NumPy array filled with zeros.

In [55]:
y=np.zeros([2,3])
y

array([[0., 0., 0.],
       [0., 0., 0.]])

3. Create a NumPy array of even numbers from 2 to 20.

In [56]:
y=np.arange(2,22,2)
y

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.

In [57]:
arr1=np.array([1,2,3])
arr2=([4,5,6])
arr3=arr1+arr2
arr3

array([5, 7, 9])

In [58]:
arr2-arr1

array([3, 3, 3])

In [59]:
arr1*arr2

array([ 4, 10, 18])

In [60]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.

In [62]:
z=np.random.rand(100)
z

array([0.70912598, 0.78030306, 0.33291861, 0.95201581, 0.99947203,
       0.17077681, 0.69187163, 0.96528184, 0.3550944 , 0.01216076,
       0.76255742, 0.74370764, 0.66771961, 0.30150352, 0.92911127,
       0.77092062, 0.67173696, 0.4222238 , 0.14290332, 0.14221719,
       0.46979664, 0.84724016, 0.91978304, 0.079527  , 0.35583063,
       0.36578175, 0.17874238, 0.61477927, 0.83855703, 0.71398639,
       0.39606322, 0.85847145, 0.55830027, 0.61175713, 0.88936736,
       0.75950578, 0.73537011, 0.90917593, 0.90613884, 0.93283109,
       0.84975715, 0.14989263, 0.20323045, 0.42378695, 0.73443611,
       0.13969788, 0.44386351, 0.41860227, 0.17928089, 0.97311701,
       0.2431803 , 0.92037383, 0.02897528, 0.66746855, 0.87530335,
       0.80842759, 0.20852054, 0.2955043 , 0.90019475, 0.74264704,
       0.00731582, 0.69570504, 0.7523137 , 0.66606982, 0.48298565,
       0.77131829, 0.12247511, 0.26586393, 0.98683881, 0.12630588,
       0.33164234, 0.1310609 , 0.81726973, 0.32388801, 0.50699

In [63]:
np.mean(z)

0.5568889180036724

In [64]:
np.median(z)

0.6098068822252463

In [65]:
np.std(z)

0.29487164902236596

6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [13]:
w=np.random.rand(12)
w

array([0.53643377, 0.08040385, 0.05815262, 0.53086394, 0.84902669,
       0.66934486, 0.73946167, 0.10708231, 0.22179769, 0.07776664,
       0.85243725, 0.63703351])

In [19]:
w.reshape(3,4)


array([[0.53643377, 0.08040385, 0.05815262, 0.53086394],
       [0.84902669, 0.66934486, 0.73946167, 0.10708231],
       [0.22179769, 0.07776664, 0.85243725, 0.63703351]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [27]:
j= np.array([1, 2, 3, 4, 5])
j

array([1, 2, 3, 4, 5])

In [28]:
np.square(j)

array([ 1,  4,  9, 16, 25])

8. Create a 5x5 identity matrix using NumPy

In [30]:
i=np.eye(5,5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]).

In [31]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [32]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [33]:
a.dot(b)


32

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [34]:
d=np.array([[1,2,3],[63,72,94],[78,56,39]])
d

array([[ 1,  2,  3],
       [63, 72, 94],
       [78, 56, 39]])

In [35]:
d.max()

94

In [36]:
d.argmax()

5

In [37]:
d.min()

1

In [38]:
d.argmin()

0

11.Concatenate two random NumPy arrays horizontally and vertically

In [140]:
c=np.random.rand(5,5)
c

array([[0.86344508, 0.93839164, 0.76137847, 0.81054201, 0.55174282],
       [0.89593106, 0.93244737, 0.50264994, 0.51850384, 0.38516046],
       [0.68624418, 0.11895349, 0.89916256, 0.41390013, 0.10086999],
       [0.0549981 , 0.11040807, 0.37111978, 0.28819988, 0.17882996],
       [0.94550936, 0.54087281, 0.61956861, 0.56973398, 0.47388244]])

In [141]:
d=np.random.rand(5,5)
d

array([[0.53071434, 0.99028321, 0.70774676, 0.76857949, 0.08733433],
       [0.66512906, 0.18029746, 0.97492871, 0.10256519, 0.87563226],
       [0.58689971, 0.6871752 , 0.23187651, 0.97402244, 0.09665596],
       [0.93231717, 0.31043587, 0.94027071, 0.61370114, 0.92289026],
       [0.99551375, 0.80998564, 0.34115663, 0.55386554, 0.61573223]])

In [142]:
np.concatenate((c,d),axis=0)

array([[0.86344508, 0.93839164, 0.76137847, 0.81054201, 0.55174282],
       [0.89593106, 0.93244737, 0.50264994, 0.51850384, 0.38516046],
       [0.68624418, 0.11895349, 0.89916256, 0.41390013, 0.10086999],
       [0.0549981 , 0.11040807, 0.37111978, 0.28819988, 0.17882996],
       [0.94550936, 0.54087281, 0.61956861, 0.56973398, 0.47388244],
       [0.53071434, 0.99028321, 0.70774676, 0.76857949, 0.08733433],
       [0.66512906, 0.18029746, 0.97492871, 0.10256519, 0.87563226],
       [0.58689971, 0.6871752 , 0.23187651, 0.97402244, 0.09665596],
       [0.93231717, 0.31043587, 0.94027071, 0.61370114, 0.92289026],
       [0.99551375, 0.80998564, 0.34115663, 0.55386554, 0.61573223]])

In [144]:
np.concatenate((c,d),axis=1)

array([[0.86344508, 0.93839164, 0.76137847, 0.81054201, 0.55174282,
        0.53071434, 0.99028321, 0.70774676, 0.76857949, 0.08733433],
       [0.89593106, 0.93244737, 0.50264994, 0.51850384, 0.38516046,
        0.66512906, 0.18029746, 0.97492871, 0.10256519, 0.87563226],
       [0.68624418, 0.11895349, 0.89916256, 0.41390013, 0.10086999,
        0.58689971, 0.6871752 , 0.23187651, 0.97402244, 0.09665596],
       [0.0549981 , 0.11040807, 0.37111978, 0.28819988, 0.17882996,
        0.93231717, 0.31043587, 0.94027071, 0.61370114, 0.92289026],
       [0.94550936, 0.54087281, 0.61956861, 0.56973398, 0.47388244,
        0.99551375, 0.80998564, 0.34115663, 0.55386554, 0.61573223]])

12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [66]:
d=np.array([[1,2,3],[63,72,94],[78,56,39],[23,66,48]])
d

array([[ 1,  2,  3],
       [63, 72, 94],
       [78, 56, 39],
       [23, 66, 48]])

In [67]:
d.sum(0)

array([165, 196, 184])

In [68]:
d.sum(1)

array([  6, 229, 173, 137])

13.Find the common elements between two NumPy arrays.

In [ ]:
d=np.array([[1,2,3],[63,72,94],[78,56,39],[23,66,48]])
d

array([[ 1,  2,  3],
       [63, 72, 94],
       [78, 56, 39],
       [23, 66, 48]])

In [70]:
p=np.array([[41,26,38],[63,92,34],[78,56,79],[53,66,48]])
p

array([[41, 26, 38],
       [63, 92, 34],
       [78, 56, 79],
       [53, 66, 48]])

In [72]:
np.intersect1d(p,d)

array([48, 56, 63, 66, 78])

14.Replace all negative values in a NumPy array with zeros.


In [ ]:
p=np.array([[41,-26,-38],[-63,92,34]])
p

array([[ 41, -26, -38],
       [-63,  92,  34]])

In [ ]:
p[p<0]=0
p

array([[41,  0,  0],
       [ 0, 92, 34]])

15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.

In [ ]:
u=np.random.randint(1,101,101)
u

array([ 91,  45,  89,   8,  93,  71,  28,  26,  32,  12,  29,  74,  47,
        15,  16,  60,  85,  55,  87,  36,  17,  29,  12, 100,  78,  67,
        33,  52,  58,  57,  36,  38,  61,   5,  57,  90,  31,  20,  20,
        69,  59,  86,  17,   9,  88,  46,  40,  63,  44,  74,  12,  62,
        37,  91,  32,   8,  84,  94,  27,   6,  66,  93, 100,   7,  51,
        36,  37,  82,  30,  13,  69,  55,  66,  91,  89,  32,  42,  83,
        22,   6,  47,  30,  20,  28,  19,   7,  16,  91,  67,  85,  98,
         6,   9,  25,  23,  80,  73,   8,  59,  50,  60])

In [ ]:
u.sort()
u

array([  5,   6,   6,   6,   7,   7,   8,   8,   8,   9,   9,  12,  12,
        12,  13,  15,  16,  16,  17,  17,  19,  20,  20,  20,  22,  23,
        25,  26,  27,  28,  28,  29,  29,  30,  30,  31,  32,  32,  32,
        33,  36,  36,  36,  37,  37,  38,  40,  42,  44,  45,  46,  47,
        47,  50,  51,  52,  55,  55,  57,  57,  58,  59,  59,  60,  60,
        61,  62,  63,  66,  66,  67,  67,  69,  69,  71,  73,  74,  74,
        78,  80,  82,  83,  84,  85,  85,  86,  87,  88,  89,  89,  90,
        91,  91,  91,  91,  93,  93,  94,  98, 100, 100])

16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [84]:
d=np.array([[916,502,309],[683,772,904],[788,596,309],[243,766,948]])
d

array([[916, 502, 309],
       [683, 772, 904],
       [788, 596, 309],
       [243, 766, 948]])

In [87]:
p=np.array([[41,726,398],[693,92,34],[78,56,79],[583,866,48]])
p

array([[ 41, 726, 398],
       [693,  92,  34],
       [ 78,  56,  79],
       [583, 866,  48]])

In [89]:
z=d-p
z


array([[ 875, -224,  -89],
       [ -10,  680,  870],
       [ 710,  540,  230],
       [-340, -100,  900]])

In [90]:
np.absolute(z)

array([[875, 224,  89],
       [ 10, 680, 870],
       [710, 540, 230],
       [340, 100, 900]])

17.Given a 2D NumPy array, extract the first row and the last column.

In [93]:
j=np.array([[875, 224,  89],
       [ 10, 680, 870],
       [710, 540, 230],
       [340, 100, 900]])
j

array([[875, 224,  89],
       [ 10, 680, 870],
       [710, 540, 230],
       [340, 100, 900]])

In [95]:
j[0]

array([875, 224,  89])

In [100]:
j[0:4,[2]]

array([[ 89],
       [870],
       [230],
       [900]])

18.Slice a 1D NumPy array to get every other element.

In [145]:
m=np.array([1,2,3,4,5,6,7,8,9])
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
m[::2]

array([1, 3, 5, 7, 9])

19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [102]:
j=np.array([[875, 224,  89,40],
       [ 10, 680, 870,334],
       [710, 540, 230,453],
       [340, 100, 900,424]])
j

array([[875, 224,  89,  40],
       [ 10, 680, 870, 334],
       [710, 540, 230, 453],
       [340, 100, 900, 424]])

In [104]:
subarray=j[1:3,[1,2]]
subarray

array([[680, 870],
       [540, 230]])

20.Reverse a 1D NumPy array using slicing.

In [123]:
m=np.array([1,2,3,4,5,6,7,8,9])
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
j=m[::-1]
j

array([9, 8, 7, 6, 5, 4, 3, 2, 1])